baseurl = "/"
title = "Marginalia"
theme = "hugo-paper"
titleCaseStyle = "AP"
reserveTaxonomyNames = true

[taxonomies]
  tag = "tags"
  author = "authors"
  book = "book"

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[[menu.main]]
    name="Search"
    url="/search"
    weight = -120

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = -100

[[menu.main]]
  name = "Authors"
  url = "/authors"
  weight = -110

[[menu.main]]
  name = "Books"
  url = "/book"
  weight = -130



[outputs]
  home = ["HTML", "RSS", "JSON"]
